### ISSUE TITLE
자연어 Keyword 추가 요청

### ISSUE THREAD

**Issue by toysmoon** [toysmoon/alfred-korean-calendar-workflow#1]
- 모레
 - today
 - tomorrow
 - 1day
 - 2day
 - 3day

**Comment by ilrara** [comment]
캘린더 이름 등록하는 방법을 좀 자세히 알려주시면 안될까요?

실행하면 오류가 발생하네요.

**Comment by toysmoon** [comment]
모레를 제외 하고 1.1.1 버전 릴리즈
