### ISSUE TITLE
여러분류의 캘린더 사용

### ISSUE THREAD

**Issue by suhyun74** [toysmoon/alfred-korean-calendar-workflow#3]
캘린더 이름 지정하면 특정 캘린더에만 일정 저장할 수 있는데 여러 이름을 등록할 수는 없는 걸까요? 잘 쓰고 있지만 이부분 약간 불편해서 연락드려요! 좋은 프로그램 만들어주셔서 감사합니다

**Comment by toysmoon** [comment]
네 어떤식으로 구현할지 고민해보고 적용시켜드릴게요.

**Comment by toysmoon** [comment]
1.2 버전에 반영되었습니다. 새로 다운로드 해주세요.
