### ISSUE TITLE
4월 추가 문제

### ISSUE THREAD

**Issue by tmdrlf123** [toysmoon/alfred-korean-calendar-workflow#4]
4월에 일정을 추가하면 1달이 더해져서 추가가 됩니다.
ex)4/2일로 추가하면 캘린더에서 5/2에 일정이 추가됩니다.

월요일 화요일로 하면 금주 해당요일에 일정을 추가 할 수 있으면 좋겠습니다.

**Comment by toysmoon** [comment]
4/2 일로 추가했을 때 저에게는 문제가 없었는데 구체적인 구현 방법을 다시 올려주시면, 확인해 보겠습니다.
해당 이슈는 클로즈 처리 하겠습니다.

요일 입력 기능은 개발해서 업데이트 하도록 하겠습니다.
